// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/waO3qFjI8yK
//  */
// import { Button } from "@/components/ui/button"
// import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"

// export function Component() {
//   return (
//     <div className="flex flex-col h-full">
//       <header className="flex items-center justify-between px-4 py-2 border-b dark:border-gray-800">
//         <h1 className="text-lg font-semibold">Admin Panel</h1>
//         <Button variant="outline">Logout</Button>
//       </header>
//       <Tabs className="flex flex-col flex-1" defaultValue="project1">
//         <TabsList className="flex px-4 py-2 border-b dark:border-gray-800">
//           <TabsTrigger value="project1">Project 1</TabsTrigger>
//           <TabsTrigger value="project2">Project 2</TabsTrigger>
//           <TabsTrigger value="project3">Project 3</TabsTrigger>
//         </TabsList>
//         <TabsContent className="flex-1 overflow-y-auto" value="project1">
//           <div className="p-4 space-y-4">
//             <h2 className="text-lg font-semibold">Users</h2>
//             <div className="grid gap-2">
//               <div className="flex items-center justify-between p-2 rounded-md bg-gray-100 dark:bg-gray-800">
//                 <span className="font-medium">John Doe</span>
//                 <div className="flex items-center gap-2">
//                   <Button size="icon" variant="ghost">
//                     <PencilIcon className="w-4 h-4" />
//                     <span className="sr-only">Edit</span>
//                   </Button>
//                   <Button size="icon" variant="ghost">
//                     <TrashIcon className="w-4 h-4" />
//                     <span className="sr-only">Delete</span>
//                   </Button>
//                 </div>
//               </div>
//               <div className="flex items-center justify-between p-2 rounded-md bg-gray-100 dark:bg-gray-800">
//                 <span className="font-medium">Jane Smith</span>
//                 <div className="flex items-center gap-2">
//                   <Button size="icon" variant="ghost">
//                     <PencilIcon className="w-4 h-4" />
//                     <span className="sr-only">Edit</span>
//                   </Button>
//                   <Button size="icon" variant="ghost">
//                     <TrashIcon className="w-4 h-4" />
//                     <span className="sr-only">Delete</span>
//                   </Button>
//                 </div>
//               </div>
//             </div>
//             <Button variant="outline">Add User</Button>
//           </div>
//         </TabsContent>
//         <TabsContent className="flex-1 overflow-y-auto" value="project2" />
//         <TabsContent className="flex-1 overflow-y-auto" value="project3" />
//       </Tabs>
//     </div>
//   )
// }


// function PencilIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
//       <path d="m15 5 4 4" />
//     </svg>
//   )
// }


// function TrashIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M3 6h18" />
//       <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
//       <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
//     </svg>
//   )
// }
